import { createElement } from '@lwc/engine-dom';
import LwcComp8_ToastMessage from 'c/lwcComp8_ToastMessage';

describe('c-lwc-comp8-toast-message', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-comp8-toast-message', {
            is: LwcComp8_ToastMessage
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});