import { createElement } from '@lwc/engine-dom';
import LwcComp6_DataTable2 from 'c/lwcComp6_DataTable2';

describe('c-lwc-comp6-data-table2', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-comp6-data-table2', {
            is: LwcComp6_DataTable2
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});